Laxmi Charitable Trust’s

Sheth L.U.J College of Arts &amp; Sir M.V. College of Science and Commerce

Department of Information Technology (Bsc.IT Semester III)

*Python for Data Science Practical*

*Practical - IV*

Roll No. : S033      
                                Name: Rudra Rawal
                                

Class : SYIT     
                                  Batch : 1

Date of Assignment : 05-08-26  
                    Date/Time of Submission : 05-08-26 
                    

In [62]:
import numpy as np

**A. Write a python code to create Numpy Array.**

In [63]:
a = np.array([1,2,3])
print(a)

[1 2 3]


**B. Write a python code to demonstrate basic operations on single array.**

In [64]:
print(a + 2)
print(a * 2)

[3 4 5]
[2 4 6]


**C. Write a python code to create array with 10 elements and slice element
from 1st to 5th element.**

In [65]:
b = np.array([1,2,3,4,5,6,7,8,9,10])
print(b[0:6])

[1 2 3 4 5 6]


**D. Write a python code to sort an array alphabetically.**

In [66]:
c = np.array(["Rudra", "Niraj", "Sumeet", "Harshal"])
print(np.sort(c))

['Harshal' 'Niraj' 'Rudra' 'Sumeet']


**E. Write a python code to create a filter array that will return maximum
values from an array.**

In [67]:
price = np.array([100,200,456,123,248,565])
print(price[price>400])

[456 565]
